# Generated by Django 5.2.16 on 2026-07-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessproduct',
            name='product_type',
            field=models.CharField(choices=[('kuku_kienyeji_live', 'Kuku wa Kienyeji (Live)'), ('kuku_kisasa_live', 'Kuku wa Kisasa (Live)'), ('vifaranga', 'Vifaranga'), ('nyama_kienyeji', 'Nyama ya Kuku Kienyeji'), ('nyama_kisasa', 'Nyama ya Kuku Kisasa'), ('mayai_kienyeji', 'Mayai ya Kienyeji'), ('mayai_kisasa', 'Mayai ya Kisasa')], max_length=50),
        ),
    ]
